version: "3.8"
services:

  backend:
    build: ./backend
    ports:
      - "3001:3000"
    volumes:
      - ./backend/src/:/app/src
    depends_on:
      - db
    restart: unless-stopped


  db:
    image: postgres
    restart: always
    environment:
      #USER postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
