version: "3.8"
services:

  web-server:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src/:/app/src
    # depends_on:
    #   - db
    restart: unless-stopped

  # db:
  #   image: postgres
  #   restart: always
  #   environment:
  #     #USER postgres
  #     POSTGRES_PASSWORD: admin
  #   volumes:
  #     - ./postgresql/data:/var/lib/postgresql/data

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - db